name: Trigger auto deployment for case2208300040006026

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/case2208300040006026-AutoDeployTrigger-c14d66aa-2ae7-4803-9c49-068071f24235.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CASE2208300040006026_REGISTRY_USERNAME }}
          password: ${{ secrets.CASE2208300040006026_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 0bbaa953/flaskapptest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CASE2208300040006026_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n case2208300040006026 -g 202209shanakura --server docker.io --username  ${{ secrets.CASE2208300040006026_REGISTRY_USERNAME }} --password ${{ secrets.CASE2208300040006026_REGISTRY_PASSWORD }}
            az containerapp update -n case2208300040006026 -g 202209shanakura --image 0bbaa953/flaskapptest:${{ github.sha }}
